
[[plugins]]
repo = 'ryanoasis/vim-devicons'


[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'lifepillar/vim-gruvbox8'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'hardcoreplayers/spaceline.vim'
hook_source = '''
	let g:spaceline_seperate_style= 'arrow'
'''


# [[plugins]]
# repo = 'glepnir/galaxyline.nvim'

[[plugins]]
repo = 'ray-x/aurora'

# [[plugins]]
# repo = 'hardcoreplayers/dashboard-nvim'
